driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  #
  # mysql_chef_gem
  #
  - name: client51-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.8'
      ]

  - name: client55-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.8',
      'debian-7.2',
      'ubuntu-14.04'
      ]

  - name: client56-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'fedora-25',
      'centos-6.8',
      'centos-7.3',
      'ubuntu-14.04'
      ]

  - name: client57-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'fedora-25',
      'centos-6.8',
      'centos-7.3'
      ]

## MariaDB
  - name: client-mariadb
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
        provider: 'mariadb'
    includes: [
      'fedora-25',
      'ubuntu-14.04'
      ]
