settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-7.1
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget
- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
  #
  # mysql_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-6.7'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'ubuntu-12.04'
    ]

  - name: client55-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'debian-7.1',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'centos-7.1',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'centos-7.1'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mysql_chef_gem_test::default]
    attributes:
      mysql_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      'fedora-21',
      'ubuntu-14.04'
    ]
