driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.1
  - name: fedora-21
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  #
  # mhysql_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-6.7'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'ubuntu-12.04'
    ]

  - name: client55-mysql
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'debian-7.1',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'centos-7.1',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-6.7',
      'centos-7.1'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mhysql_chef_gem_test::default]
    attributes:
      mhysql_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      'fedora-21',
      'ubuntu-14.04'
    ]
